name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
        run: |
          # Debug: mostrar valores mascarados das vari치veis
          echo "Checking if variables are set (values will be masked):"
          echo "API_KEY: ${VITE_FIREBASE_API_KEY:0:5}..."
          echo "AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN:0:5}..."
          echo "PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID:0:5}..."
          
          # Verificar vari치veis
          missing_vars=()
          for var in VITE_FIREBASE_API_KEY VITE_FIREBASE_AUTH_DOMAIN VITE_FIREBASE_PROJECT_ID VITE_FIREBASE_STORAGE_BUCKET VITE_FIREBASE_MESSAGING_SENDER_ID VITE_FIREBASE_APP_ID; do
            if [ -z "${!var}" ]; then
              missing_vars+=($var)
            else
              echo "$var is set"
            fi
          done
          
          # Se houver vari치veis faltando, mostrar erro
          if [ ${#missing_vars[@]} -ne 0 ]; then
            echo "Error: The following variables are not set:"
            printf '%s\n' "${missing_vars[@]}"
            exit 1
          fi
          
          # Se todas as vari치veis estiverem ok, fazer o build
          echo "All variables are set, proceeding with build..."
          npm run build
        
      - name: Create .nojekyll file
        run: |
          touch dist/.nojekyll
          cp dist/index.html dist/404.html
          echo "ahorademudar.com.br" > dist/CNAME
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: dist
          clean: true